### ISSUE TITLE
Small Bugs List

### ISSUE THREAD

**Issue by TianjiaSun** [Yubin/web_desktop#8]
- [x] Single-click open fails frequently. It easily and falsely takes single-click as drag and drop. 
- [x] When drag and drop, delay a little bit to hide header. Use fade-out to hide header.
- [x] To delete an app, drop the app in trash area to delete, instead of touching the trash area to delete.
- [x] Limit APP position in the area of panels. 
- [x] When open an app from search result, close search result when "open" is clicked. 
- [x] When there are multiple apps opened. Click content of an app should be able to activate the app and make it in front. Now, only click the header of the app can. 
- [x] Hint the drop position dynamically for drag and drop. 
- [x] When APP is drag on top of a panel, fade-in the panel.

**Comment by Yubin** [comment]
All are done
